server:
  port: 9999
spring:
  mvc:
    servlet:
      path: /api
  application:
    name: ddd-demo
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/student
    username: root
    password: root
  data:
    redis:
      database: 0
      host: localhost
      port: 6379
  main:
    allow-circular-references: true
  elasticsearch:
    uris: 192.168.200.129:9200
    password: root
    username: elastic
jwt:
  expTime: PT1H
  secretKey: administrator
logging:
  level:
    cn.rzpt: debug
  file:
    path: logs
    name: ${logging.file.path}/${spring.application.name}.log
knife4j:
  enable: true
  setting:
    language: zh_cn
